"use client";

import React from "react";
import Link from "next/link";
import BrandLogo from "@/components/BrandLogo";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white dark:bg-[#09090b] text-gray-900 dark:text-white px-6 py-20 transition-colors duration-500 bg-dot-pattern">
            <div className="max-w-3xl mx-auto space-y-12">
                <div className="flex flex-col items-center gap-8">
                    <Link href="/" className="hover:opacity-80 transition-opacity">
                        <BrandLogo size="md" />
                    </Link>
                    <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-center">
                        Terms of Service
                    </h1>
                </div>

                <div className="prose prose-indigo dark:prose-invert max-w-none space-y-8 font-medium text-gray-600 dark:text-gray-400 leading-relaxed">
                    <section className="space-y-4">
                        <h2 className="text-lg font-black uppercase tracking-[0.2em] text-indigo-500">The Ground Rules</h2>
                        <p>
                            By using MindMint, you agree to these simple terms. We&apos;ve kept them short so you actually have time to study!
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 dark:text-white">Service Description</h3>
                        <p>
                            MindMint is an AI-powered study tool designed to help you organize and understand information better. It generates study aids based on the text you provide.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 dark:text-white">No Guarantee of Accuracy</h3>
                        <p>
                            MindMint uses artificial intelligence to generate content. While we strive for quality, we cannot guarantee that the outputs will always be accurate, complete, or free of errors.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 dark:text-white">User Responsibility</h3>
                        <p>
                            You are responsible for how you use the materials generated by MindMint. We recommend cross-referencing AI-generated content with your official textbooks or sources.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 dark:text-white">Not Professional Advice</h3>
                        <p>
                            MindMint does not provide professional medical, legal, financial, or other specialized advice. All content is for educational and informational purposes only.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <h3 className="text-sm font-black uppercase tracking-widest text-gray-900 dark:text-white">Feature Updates</h3>
                        <p>
                            As a growing startup, we may add, update, or discontinue certain features to improve the overall experience.
                        </p>
                    </section>
                </div>

                <div className="pt-12 text-center">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-3 px-8 py-4 bg-indigo-600 hover:bg-indigo-700 text-white font-black rounded-full transition-all shadow-xl shadow-indigo-600/20 active:scale-95"
                    >
                        ← Back to Home
                    </Link>
                </div>
            </div>
        </div>
    );
}
