"use client";

import React from "react";
import Link from "next/link";
import BrandLogo from "@/components/BrandLogo";

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen bg-white dark:bg-[#09090b] text-gray-900 dark:text-white px-6 py-20 transition-colors duration-500 bg-dot-pattern">
            <div className="max-w-3xl mx-auto space-y-12">
                <div className="flex flex-col items-center gap-8">
                    <Link href="/" className="hover:opacity-80 transition-opacity">
                        <BrandLogo size="md" />
                    </Link>
                    <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-center">
                        AI Disclaimer
                    </h1>
                </div>

                <div className="prose prose-indigo dark:prose-invert max-w-none space-y-8 font-medium text-gray-600 dark:text-gray-400 leading-relaxed text-center">
                    <section className="space-y-6">
                        <div className="inline-block p-4 bg-amber-500/10 border border-amber-500/20 rounded-3xl">
                            <span className="text-xl">⚠️</span>
                        </div>
                        <h2 className="text-lg font-black uppercase tracking-[0.2em] text-amber-500">Important Heads Up</h2>
                        <p className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-gray-900 to-gray-600 dark:from-white dark:to-gray-400">
                            Every mindmap, quiz, and summary you see here is generated by Artificial Intelligence.
                        </p>
                    </section>

                    <section className="space-y-4 pt-8 text-left">
                        <p>
                            While AI is incredibly powerful, it's not perfect. It can occasionally:
                        </p>
                        <ul className="list-none space-y-4">
                            <li className="flex items-start gap-3">
                                <span className="text-indigo-500 font-bold block mt-1">•</span>
                                <span>Get facts wrong or "hallucinate" information.</span>
                            </li>
                            <li className="flex items-start gap-3">
                                <span className="text-indigo-500 font-bold block mt-1">•</span>
                                <span>Miss subtle nuances or context from your original text.</span>
                            </li>
                            <li className="flex items-start gap-3">
                                <span className="text-indigo-500 font-bold block mt-1">•</span>
                                <span>Provide inconsistent results for the same input.</span>
                            </li>
                        </ul>
                    </section>

                    <section className="space-y-4 pt-8 text-left italic">
                        <p className="text-gray-900 dark:text-white font-bold">
                            We strongly recommend fact-checking any critical information with your primary study materials or teachers. MindMint is a helper, not a substitute for accurate verification.
                        </p>
                    </section>
                </div>

                <div className="pt-12 text-center">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-3 px-8 py-4 bg-indigo-600 hover:bg-indigo-700 text-white font-black rounded-full transition-all shadow-xl shadow-indigo-600/20 active:scale-95"
                    >
                        ← Back to Home
                    </Link>
                </div>
            </div>
        </div>
    );
}
